# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74b81c8f19dd527380b628b6382b3113a0d06b5b719929c4e1c18c5e6a99a833d2d5c4295a0c8ef67f0db1e56b7e0c4b97ae30616d2e1e24ef44aa7511e1b212

test:
  secret_key_base: 52ccd12077a643458d6d6413b5521adbec0da5a6e73f99248ea69aa1d6cef88e821b88d70d5d67d680e4cc03d97f8a821904deadda957b26720d5fbf2b55203c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
